/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ProfessorObjectPageObjectPage journey");

        opaTest("Navigate to ProfessorObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheProfessorList.onFilterBar().iExecuteSearch();

            Then.onTheProfessorList.onTable().iCheckRows();
            When.onTheProfessorList.onTable().iPressRow(0);

            Then.onTheProfessorObjectPage.iSeeThisPage();
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheProfessorObjectPage.iCheckNumberOfSections(3);
            When.onTheProfessorObjectPage.iPressSectionIconTabFilterButton("ProfessorDetails");
            Then.onTheProfessorObjectPage.iCheckSection({ section: "ProfessorDetails" });
            Then.onTheProfessorObjectPage.onForm({ section: "ProfessorDetails" }).iCheckField({ property: "ProfessorId" });
            Then.onTheProfessorObjectPage.onForm({ section: "ProfessorDetails" }).iCheckField({ property: "Email" });
            Then.onTheProfessorObjectPage.onForm({ section: "ProfessorDetails" }).iCheckField({ property: "FirstName" });
            Then.onTheProfessorObjectPage.onForm({ section: "ProfessorDetails" }).iCheckField({ property: "LastName" });
            Then.onTheProfessorObjectPage.onForm({ section: "ProfessorDetails" }).iCheckField({ property: "Photo" });
            When.onTheProfessorObjectPage.iPressSectionIconTabFilterButton("ProfessorDepartments");
            Then.onTheProfessorObjectPage.iCheckSection({ section: "ProfessorDepartments" });
            When.onTheProfessorObjectPage.iPressSectionIconTabFilterButton("ProfessorCourses");
            Then.onTheProfessorObjectPage.iCheckSection({ section: "ProfessorCourses" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});